//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Владелец> Владелец { get; set; }
        public virtual DbSet<Договор> Договор { get; set; }
        public virtual DbSet<Подготовка_к_соревнованиям> Подготовка_к_соревнованиям { get; set; }
        public virtual DbSet<Результат> Результат { get; set; }
        public virtual DbSet<Секция> Секция { get; set; }
        public virtual DbSet<Соревнования> Соревнования { get; set; }
        public virtual DbSet<Сотрудники> Сотрудники { get; set; }
        public virtual DbSet<Спортивный_клуб> Спортивный_клуб { get; set; }
        public virtual DbSet<Спортсмен> Спортсмен { get; set; }
        public virtual DbSet<Тренер> Тренер { get; set; }
    }
}
