//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class Подготовка_к_соревнованиям
    {
        [Key]
        public int ID_Тренировки { get; set; }
        public Nullable<System.DateTime> Дата_тренировки { get; set; }
        public Nullable<int> ID_Спорт_клуба { get; set; }
        public Nullable<int> ID_Группы { get; set; }
        public Nullable<int> ID_Тренера { get; set; }
        public Nullable<int> ID_Соревнования { get; set; }
        public Nullable<int> Соревнования_ID_Соревнований { get; set; }
    
        public virtual Секция Секция { get; set; }
        public virtual Соревнования Соревнования { get; set; }
        public virtual Спортивный_клуб Спортивный_клуб { get; set; }
        public virtual Тренер Тренер { get; set; }
    }
}
