//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class Результат
    {
        [Key]
        public int ID_Результата { get; set; }
        public string Занятое_место { get; set; }
        public Nullable<System.DateTime> Время { get; set; }
        public Nullable<int> Набрано_очков { get; set; }
        public Nullable<int> ID_Соревнования { get; set; }
        public Nullable<int> Соревнования_ID_Соревнований { get; set; }
    
        public virtual Соревнования Соревнования { get; set; }
        public virtual Спортсмен Спортсмен { get; set; }
    }
}
