//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class Соревнования
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        //public Соревнования()
        //{
        //    this.Подготовка_к_соревнованиям = new HashSet<Подготовка_к_соревнованиям>();
        //}
        [Key]
        public int ID_Соревнований { get; set; }
        public Nullable<System.DateTime> Дата_соревнований { get; set; }
        public string Тип_соревнований { get; set; }
        public string Вид_спорта { get; set; }
        public string Спонсор_соревнований { get; set; }
        public string Город { get; set; }
        public string Адрес { get; set; }


        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Спортсмен> Спортсменs { get; set; }
        public virtual ICollection<Сотрудники> Сотрудникиs  { get; set; }
        //        public virtual ICollection<Подготовка_к_соревнованиям> Подготовка_к_соревнованиям { get; set; }
        //      public virtual Результат Результат { get; set; }
    }
}
