//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class Сотрудники
    {
        [Key]
        public int ID_Сотрудника { get; set; }
        public string Имя { get; set; }
        public string Фамилия { get; set; }
        public string Отчество { get; set; }
        public Nullable<int> Телефон { get; set; }
        public string Должность { get; set; }
        public string Общий_стаж { get; set; }
        public Nullable<decimal> Зарплата { get; set; }
        public Nullable<int> ID_Спорт_клуба { get; set; }
    
        public virtual Спортивный_клуб Спортивный_клуб { get; set; }
        //public virtual Тренер Тренер { get; set; }
    }
}
