//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class Спортсмен
    {
        [Key, ForeignKey("Результат")]
        
        public int ID_Спортсмена { get; set; }
  
        public string Имя { get; set; }
        public string Фамилия { get; set; }
        public Nullable<bool> Пол { get; set; }
        public Nullable<System.DateTime> Дата_рождения { get; set; }
        public Nullable<int> Телефон { get; set; }
    
        public virtual Договор Договор { get; set; }
        public virtual Результат Результат { get; set; }
    }
}
