//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class Спортсмен
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int ID_Спортсмена { get; set; }
  
        public string Имя { get; set; }
        public string Фамилия { get; set; }
        public Nullable<bool> Пол { get; set; }
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:dd/MM/yyyy}")]
        public Nullable<System.DateTime> Дата_рождения { get; set; }
        public string Группа { get; set; }
        public Nullable<int> Телефон { get; set; }
        public string Гражданство { get; set; }
        public ulong Серия_номер_паспорта { get; set; }
        public string Адрес_проживания { get; set; }
                     
        //public virtual Договор Договор { get; set; }


    }
}
