//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class Спортивный_клуб
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Спортивный_клуб()
        {
            //this.Подготовка_к_соревнованиям = new HashSet<Подготовка_к_соревнованиям>();
            this.Сотрудники = new HashSet<Сотрудники>();
        }
        [Key, ForeignKey("Сотрудники")]
        public int ID_Спорт_клуба { get; set; }
        public string Название { get; set; }
        public string Адрес { get; set; }
        public Nullable<int> Телефон { get; set; }
        public Nullable<bool> Сауна { get; set; }
        public Nullable<bool> Тренажерный_зал { get; set; }
        public Nullable<bool> Бассейн { get; set; }
        public Nullable<bool> Бар { get; set; }
        public Nullable<bool> Массажный_кабинет { get; set; }
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:dd/MM/yyyy}")]
        public Nullable<DateTime> Дата_основания { get; set; }
    
       // public virtual Владелец Владелец { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        //public virtual ICollection<Подготовка_к_соревнованиям> Подготовка_к_соревнованиям { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Сотрудники> Сотрудники { get; set; }
        public virtual ICollection<Спортсмен> Спортсменs { get; set; }
    }
}
