//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class Тренер
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Тренер()
        {
            this.Подготовка_к_соревнованиям = new HashSet<Подготовка_к_соревнованиям>();
        }
        [Key, ForeignKey("Сотрудники")]
        public int ID_Тренера { get; set; }
        public string Спортивный_разряд { get; set; }
        public string Вид_спорта { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Подготовка_к_соревнованиям> Подготовка_к_соревнованиям { get; set; }
        public virtual Секция Секция { get; set; }
        public virtual Сотрудники Сотрудники { get; set; }
    }
}
